dependencies:
- name: postgresql
  condition: postgresql.enabled
- name: redis
  condition: redis.enabled
- name: octopipe-charlescd
  condition: octopipe.enabled
- name: envoy
  condition: envoy.enabled
- name: keycloak
  condition: keycloak.enabled