codecov:
  require_ci_to_pass: yes
  
coverage:
  status:
    project:
      default: off
      villager:
        target: 50%
        flags: 
          - villager

flags:
  villager:
    paths:
      - villager/
    carryforward: true
