coverage:
  precision: 2
  round: nearest
  range: 50...60
  
  status:
    project:
      default: off
      villager:
        target: 80%
        flags: 
          - villager
        if_ci_failed: error
    patch:
      default: off
      villager:
        target: 80%
        flags: 
          - villager
        if_ci_failed: error
    changes:
      default: off
      villager:
        target: 80%
        flags: 
          - villager
        if_ci_failed: error

flags:
  villager:
    paths:
      - villager/
    carryforward: true
