coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        flags: 
          - villager
          - circlematcher
          - octopipe
          - butler
          - ui
          - moove
      villager:
        target: 30%
        flags:
          - villager
      circlematcher:
        target: 70%
        flags:
          - circlematcher
      octopipe:
        target: 70%
        flags:  
          - octopipe
      butler:
        target: 30%
        flags:  
          - butler
      ui:
        target: 30%
        flags:  
          - ui
      moove:
        target: 30%
        flags:  
          - moove
    patch:
      default:
        target: 100%
        threshold: 0%
        flags: 
          - villager
          - circlematcher
          - octopipe
          - butler
          - ui
          - moove
      
flags:
  villager:
    paths:
      - villager/
    carryforward: true
  circlematcher:
    paths:
      - circle-matcher/
    carryforward: true
  octopipe:
    paths:
      - octopipe/
    carryforward: true
  butler:
    paths:
      - butler/
    carryforward: true
  ui:
    paths:
      - ui/
    carryforward: true
  moove:   
    paths:
      - moove/
    carryforward: true    