coverage:  
  status:
    project:
      villager:
        target: 80%
        paths:
          - villager/*
        flags: 
          - villager
        if_ci_failed: error
    patch:
      villager:
        target: 80%
        paths:
          - villager/*
        flags: 
          - villager
        if_ci_failed: error
    changes: off

flags:
  villager:
    paths:
      - villager/*
    carryforward: true
