databaseChangeLog:
  - changeSet:
      id: 20190717142200-1
      author: lucas.fernandes
      comment: "Create table modules_labels"
      changes:
      - createTable:
          tableName: modules_labels
          columns:
          - column:
              name: module_id
              type: varchar(36)
              autoIncrement: false
              constraints:
                primaryKey: true
                nullable: false
          - column:
              name: label_id
              type: varchar(36)
              constraints:
                primaryKey: true
                nullable: false
