databaseChangeLog:
  - changeSet:
      id: 20190911173500-1
      author: mateus.cruz
      comment: "Create table credential_configurations"
      changes:
        - createTable:
            tableName: credential_configurations
            columns:
              - column:
                  name: id
                  type: varchar(36)
                  autoIncrement: false
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: varchar(64)
                  constraints:
                    nullable: false
              - column:
                  name: type
                  type: varchar(64)
                  constraints:
                    nullable: false
              - column:
                  name: created_at
                  type: timestamp
                  constraints:
                    nullable: false
              - column:
                  name: user_id
                  type: varchar(64)
                  constraints:
                    foreignKeyName: fk_credential_configurations_users
                    references: users(id)
                    nullable: false
