databaseChangeLog:
  - changeSet:
      id: 20200305146000-1
      author: adauto.paula
      comment: "Create table artifact_snapshots"
      changes:
        - createTable:
            tableName: artifact_snapshots
            columns:
              - column:
                  name: id
                  type: varchar(36)
                  autoIncrement: false
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: artifact
                  type: varchar(64)
                  constraints:
                    nullable: false
              - column:
                  name: version
                  type: varchar(64)
                  constraints:
                    nullable: false
              - column:
                  name: created_at
                  type: timestamp
                  constraints:
                    nullable: false
              - column:
                  name: component_snapshot_id
                  type: varchar(36)
                  constraints:
                    foreignKeyName: fk_as_component_snapshot_id
                    references: component_snapshots(id)
                    nullable: false

