databaseChangeLog:
  - changeSet:
      id: 20200207143000-1
      author: mateus.cruz
      comment: "Create table applications"
      changes:
        - createTable:
            tableName: applications
            columns:
              - column:
                  name: id
                  type: varchar(36)
                  autoIncrement: false
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: varchar(64)
                  constraints:
                    nullable: false