databaseChangeLog:
  - changeSet:
      id: 20200113154500-1
      author: mateus.cruz
      comment: "Fixing foreign keys relations"
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: hypothesis_id
            baseTableName: builds
            constraintName: fk_builds_hypothesis_id
            referencedColumnNames: id
            referencedTableName: hypotheses
        - addForeignKeyConstraint:
            baseColumnNames: build_id
            baseTableName: builds_features
            constraintName: fk_builds_features_build_id
            referencedColumnNames: id
            referencedTableName: builds
        - addForeignKeyConstraint:
            baseColumnNames: feature_id
            baseTableName: builds_features
            constraintName: fk_builds_features_feature_id
            referencedColumnNames: id
            referencedTableName: features
        - addForeignKeyConstraint:
            baseColumnNames: hypothesis_id
            baseTableName: cards
            constraintName: fk_cards_hypothesis_id
            referencedColumnNames: id
            referencedTableName: hypotheses
        - addForeignKeyConstraint:
            baseColumnNames: card_id
            baseTableName: cards_labels
            constraintName: fk_cards_labels_card_id
            referencedColumnNames: id
            referencedTableName: cards
        - addForeignKeyConstraint:
            baseColumnNames: label_id
            baseTableName: cards_labels
            constraintName: fk_cards_labels_label_id
            referencedColumnNames: id
            referencedTableName: labels
        - addForeignKeyConstraint:
            baseColumnNames: feature_id
            baseTableName: features_modules
            constraintName: fk_features_modules_feature_id
            referencedColumnNames: id
            referencedTableName: features
        - addForeignKeyConstraint:
            baseColumnNames: module_id
            baseTableName: features_modules
            constraintName: fk_features_modules_module_id
            referencedColumnNames: id
            referencedTableName: modules
        - addForeignKeyConstraint:
            baseColumnNames: hypothesis_id
            baseTableName: hypotheses_circles
            constraintName: fk_hypotheses_circles_hypothesis_id
            referencedColumnNames: id
            referencedTableName: hypotheses
        - addForeignKeyConstraint:
            baseColumnNames: circle_id
            baseTableName: hypotheses_circles
            constraintName: fk_hypotheses_circles_circle_id
            referencedColumnNames: id
            referencedTableName: circles
        - addForeignKeyConstraint:
            baseColumnNames: hypothesis_id
            baseTableName: hypotheses_labels
            constraintName: fk_hypotheses_labels_hypothesis_id
            referencedColumnNames: id
            referencedTableName: hypotheses
        - addForeignKeyConstraint:
            baseColumnNames: label_id
            baseTableName: hypotheses_labels
            constraintName: fk_hypotheses_labels_label_id
            referencedColumnNames: id
            referencedTableName: labels
        - addForeignKeyConstraint:
            baseColumnNames: module_id
            baseTableName: modules_configurations
            constraintName: fk_modules_configurations_module_id
            referencedColumnNames: id
            referencedTableName: modules
        - addForeignKeyConstraint:
            baseColumnNames: configuration_id
            baseTableName: modules_configurations
            constraintName: fk_modules_configurations_configuration_id
            referencedColumnNames: id
            referencedTableName: credential_configurations
        - addForeignKeyConstraint:
            baseColumnNames: module_id
            baseTableName: modules_labels
            constraintName: fk_modules_labels_module_id
            referencedColumnNames: id
            referencedTableName: modules
        - addForeignKeyConstraint:
            baseColumnNames: label_id
            baseTableName: modules_labels
            constraintName: fk_modules_labels_label_id
            referencedColumnNames: id
            referencedTableName: labels
        - addForeignKeyConstraint:
            baseColumnNames: value_flow_id
            baseTableName: value_flows_labels
            constraintName: fk_value_flows_labels_value_flow_id
            referencedColumnNames: id
            referencedTableName: value_flows
        - addForeignKeyConstraint:
            baseColumnNames: label_id
            baseTableName: value_flows_labels
            constraintName: fk_value_flows_labels_label_id
            referencedColumnNames: id
            referencedTableName: labels