version: '3'
services:

  postgres:
    image: postgres:9.6-alpine
    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=darwin
    - POSTGRES_USER=darwin
    - POSTGRES_PASSWORD=darwin
    - MAX_CONNECTIONS=300

  stubby4j:
    image: sandokandias/stubby4j-docker
    ports:
    - 8883:8883
    environment:
      STUBBY_PORT: 8883
    volumes:
    - ./src/app/resources/stubby/integrations.yml:/usr/local/stubby.yml
