---
{{- if .Values.CharlesApplications.butler.enabled}}
apiVersion: v1
data:
  encryption-key: QzYzOUE1NzJFMTRENTA3NUM1MjZGRERENDNFNEVDRjZCMDk1RUExNzc4M0QzMkVGM0QyNzEwQUY5RjM1OURENA==
kind: Secret
metadata:
  name: deploy-aes256-key
type: Opaque
---
{{- end }}

{{- if .Values.CharlesApplications.compass.enabled }}
apiVersion: v1
data:
  encryption-key: NmRkZGU0MTAtM2YxYi0xMWViLWIzNzgtMDI0MmFjMTMwMDAy
kind: Secret
metadata:
  name: compass-aes256-key
type: Opaque
---
{{- end }}

{{- if or .Values.CharlesApplications.moove.enabled .Values.CharlesApplications.butler.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: application-aes256-key
type: Opaque
data:
  encryption-key: OGVhMzY4OGYtYmUxOS00YWU2LTljNmMtZDFhNjAzNjAyYTJm
---
{{- end }}

{{- if .Values.CharlesApplications.hermes.enabled }}
apiVersion: v1
data:
  encryption-key: Yjg0NDVkMDUtMzliOC00YTkxLWEwOWMtZDRhN2VkOGRlZmRj
kind: Secret
metadata:
  name: hermes-aes256-key
type: Opaque
---
{{- end }}

{{- if or .Values.CharlesApplications.moove.enabled .Values.CharlesApplications.gate.enabled }}
apiVersion: v1
data:
  encryption-key: NjQ5NzE5MjNkMjFhNDg4N2EzYWNmMWFkMTU5NjFiYmM=
kind: Secret
metadata:
  name: gate-aes256-key
type: Opaque
---
{{- end }}

{{- if .Values.rabbitmq.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: charlescd-rabbitmq-erl
data:
  rabbitmq-erlang-cookie: bWkyYVJyUnBFSldSQ05heW1hWWU3UTZWclYyRHVLcG8=
type: Opaque
---
{{- end }}
{{- if or .Values.CharlesApplications.moove.enabled .Values.CharlesApplications.butler.enabled }}
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUYrekNDQStPZ0F3SUJBZ0lVUjMwR3h4dnFsS2ptYUdNTVVoUTZUYjMxM1Jnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dZd3hDekFKQmdOVkJBWVRBa0pTTVJJd0VBWURWUVFJREFsVFFVOWZVRUZWVEU4eEN6QUpCZ05WQkFjTQpBbE5RTVF3d0NnWURWUVFLREFOYVZWQXhFVEFQQmdOVkJBc01DRkJTVDBSVlExUlRNUkF3RGdZRFZRUUREQWREClNFRlNURVZUTVNrd0p3WUpLb1pJaHZjTkFRa0JGaHAwYUdGc2JHVnpMbVp5WldsMFlYTkFlblZ3TG1OdmJTNWkKY2pBZUZ3MHlNVEExTWpFeE1qVTROREphRncweU1qQTFNakV4TWpVNE5ESmFNSUdNTVFzd0NRWURWUVFHRXdKQwpVakVTTUJBR0ExVUVDQXdKVTBGUFgxQkJWVXhQTVFzd0NRWURWUVFIREFKVFVERU1NQW9HQTFVRUNnd0RXbFZRCk1SRXdEd1lEVlFRTERBaFFVazlFVlVOVVV6RVFNQTRHQTFVRUF3d0hRMGhCVWt4RlV6RXBNQ2NHQ1NxR1NJYjMKRFFFSkFSWWFkR2hoYkd4bGN5NW1jbVZwZEdGelFIcDFjQzVqYjIwdVluSXdnZ0lpTUEwR0NTcUdTSWIzRFFFQgpBUVVBQTRJQ0R3QXdnZ0lLQW9JQ0FRREhhVFhwdmZua2pNdERwY0JvOGhjVGpLQkVnZEhpNXo4YWhWa0hRRDQ0Cm9UNlRJcVpNUW0zQ0M3K0F5Tkg0R3pxVm5ETm5YT1VwUnEyUjh2WWdwQmNOT0t1S2QvbjNhQ0VidkdTOFArRE8KUjh4Y0tNVk01R08rVlFLNDQvZWRaZExuMlJoN09RWjFXKzhtNzRMOXJKbitJMGZyVEJ0WFhkUjJaaGYzN24vYgpuSEtFUEppaTBIdU1QWUZ4UFJ0QXZQNGU1bzFQUWlJWWg5TE9FSE1CcEllTG9WNVBrUXEzaVg3b1lGWGJmOVl3CnZ3ZHJFSzhEWmVrWjZiUnE2Wm0yckVGRXd0WllKWFZXWWVpK2Z5eHNLL0UrWmtCSVZZN0NvcnVqRDc3UHVidkcKcWtFQUttU2F2eTg4RzNmU2NBQ3JPSnJSMU1SUE02WDZhUlNOQ0ZLUE84NXBJV2laQXNSdXVPK01hQTlOeGhCbApwbTVDa3hBTkpBY1ZHRUIrNHRMZ283NjlZam1IRkxsWUZhYmd1azZFNVhtTlVTSW42MFJYZUt5US84eGtZcHRaClJlMXQvN24yZ1VBekNuaEhNV2pMZStPOTJzZHN2eFlyZkVDdFhhOUhTbVJ2MXdHamQvMm80eUJCb0RmRWg3V2cKTG5KWXkvZzBockFRM3V0SEpCWE1TNmYybU5NbkxURzhxOUFVRzUxdDlqQU9QWkFPMFU0d05IMHVIYk9CczM4awpoN28yS1JRYU9ob3dPRnRDK2dGT3BYRVZKaFVaVWR4Y2dtTVlHRUFVcHd6bGVkYW9oY1VGWmN4NlhuYWJvTFU4Cnp5czlSTGRsQTlURHhiUmFrd1EyRWZBWlZ5YVpaTHcxTXBkSDhQNnVnRzh3QTlESXBCakpIdUVFNzl3TjRsZVYKSlFJREFRQUJvMU13VVRBZEJnTlZIUTRFRmdRVUlFRjZGL2oybElsSkowNFc3QnN1bFA3cmpQVXdId1lEVlIwagpCQmd3Rm9BVUlFRjZGL2oybElsSkowNFc3QnN1bFA3cmpQVXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txCmhraUc5dzBCQVFzRkFBT0NBZ0VBTjdUeFBDejRESkF0czRoeVg1YzYyZnFwdDhzSlpsRDhJME1ablZ5RU40S3oKYkgyYnBoTjJBTGcvZUV0RUlWdkZ3MklVWUw2UTFaNG9kWklDMXJIUFBPbXE2b21leGhPekIweFdFcmpjRlZzYwphRFUrZUlCbHQwNmdvVVpSaVBGakVCcFBHalBzYW1mcU9uWmtzWm91bVg3RVZJY21aNDUvcE9RaytEekVnRHU0CnJlU2I4L0dpK3p3aFM0YnlnelNVWGVvY21yejB6RGtKbGpGNndieVEwMXhPWDdUbGVUdDZ1bEE1cE5jOFpKWi8KZC9VVjVtSVU2OWhOWXJ0ZjZpV0xub3c4Nk85VzhiTlhYNWt4OTgxZHdvTVFBbVY0aFJBOHFaMzRDbENDa1ZKQQp2eHBiODhjTGl4VWViZFhCZ1Z0Y2NiV1NBVE05amxVY1NvbEFGZytTOEpXRXlqMHQzMGc4VklreEprYzlhSS92CnpwdTE2clFoVzBXSWNQQm1OL3hSbWM1RWdCMHdPUTdPeFB3ZU9FQXBGbjhxMkJoU25BRTIxcnZvZ0VjbEN6OWUKQU1odGx3ZFc1bDhBS0JJRTJ1UmlLQkpERWJSOXNEOHg1dDNQVUJxR3o0TE8wTWFsSEoycmQzN25WaUJlcVl1TApkbWovcXdJb1BnOUNHYzlqSzdZR2crQmtHRllyalNjNHRLSXhMVnFsYU5udEJKbTh6UnhIcVVHajBTUTlVQ2l0CnVpNitPR3FOZWVLZWpNZ0ZQdTRTKzM4N1psUksrUzVqUDEzdXFBazExelBZRFN0ZU5ld0xqam9CcFlRRndrSXIKdDlHdFg4MXVUOUJKclV0VFgzczhYeXhQYlpaM09aSVJIeFQrRDNOV2U2d0NFeFg1SDROQUNneWlWRC85WVVBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRUUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQ1Nzd2dna25BZ0VBQW9JQ0FRREhhVFhwdmZua2pNdEQKcGNCbzhoY1RqS0JFZ2RIaTV6OGFoVmtIUUQ0NG9UNlRJcVpNUW0zQ0M3K0F5Tkg0R3pxVm5ETm5YT1VwUnEyUgo4dllncEJjTk9LdUtkL24zYUNFYnZHUzhQK0RPUjh4Y0tNVk01R08rVlFLNDQvZWRaZExuMlJoN09RWjFXKzhtCjc0TDlySm4rSTBmclRCdFhYZFIyWmhmMzduL2JuSEtFUEppaTBIdU1QWUZ4UFJ0QXZQNGU1bzFQUWlJWWg5TE8KRUhNQnBJZUxvVjVQa1FxM2lYN29ZRlhiZjlZd3Z3ZHJFSzhEWmVrWjZiUnE2Wm0yckVGRXd0WllKWFZXWWVpKwpmeXhzSy9FK1prQklWWTdDb3J1akQ3N1B1YnZHcWtFQUttU2F2eTg4RzNmU2NBQ3JPSnJSMU1SUE02WDZhUlNOCkNGS1BPODVwSVdpWkFzUnV1TytNYUE5TnhoQmxwbTVDa3hBTkpBY1ZHRUIrNHRMZ283NjlZam1IRkxsWUZhYmcKdWs2RTVYbU5VU0luNjBSWGVLeVEvOHhrWXB0WlJlMXQvN24yZ1VBekNuaEhNV2pMZStPOTJzZHN2eFlyZkVDdApYYTlIU21SdjF3R2pkLzJvNHlCQm9EZkVoN1dnTG5KWXkvZzBockFRM3V0SEpCWE1TNmYybU5NbkxURzhxOUFVCkc1MXQ5akFPUFpBTzBVNHdOSDB1SGJPQnMzOGtoN28yS1JRYU9ob3dPRnRDK2dGT3BYRVZKaFVaVWR4Y2dtTVkKR0VBVXB3emxlZGFvaGNVRlpjeDZYbmFib0xVOHp5czlSTGRsQTlURHhiUmFrd1EyRWZBWlZ5YVpaTHcxTXBkSAo4UDZ1Z0c4d0E5RElwQmpKSHVFRTc5d040bGVWSlFJREFRQUJBb0lDQUdkSkJtUzRRcXZ2aFFUWDRHNDdIbHJBCjF1NUU4NHA4VGtJVldZU1k4T0Z5R3pBb25Vd1lpRE1lMUtVRzMwS01EKzhZQmNQKzZLOVZiV2VRR1kzVWtDQUgKLzBuc1ZLdWg0cXcwQzFVNkhOMmJjSzAzYk9JajFjbnF6RXNwd01KazBEWElTNWJmZFlucUFWZ0FiSytwNitVbgpMd1FmMm5XSkl4ZmtUM3ZhcTV6N1RwRlJ0WmwzTk5ieHNJOFBvSU1Lb1BFdVozanEvekFIZ2RlN3kyWEphMitXCk9Id3Iyd292akcwZUlMcGRYM3JHSnpoOFhybjYyaDdTM3VFVmQ4bVhOUU5CaTdZQ1NPRmlPeVFZU05FS2ZaemQKWjJSUDlHNjV6VWhyU21EYmlmZ2ZqU1ZoejlRYlBJTDhremFMVHIxZ3gwZngxWEJVaHg3SnVKeEgrRU02TGZGNQpBaFcwNDdxWlNjbXNHdDJjQXV6WisxOGc1TWVTSUI5RVJPVDlDVldlaTVGcWlnOUg2SU5LdmsvcmJBdmh4K2s0CmNaY0tBSUpMSmpzbkhiUW9RV1hkTmpuYmIwYi9CM3BTS0d6VTR2REVVdXRSUmRIOFN1UTMrSXVkWXh1bWhkMVgKOFVyMFJ5NVA2cUtZZVBvR1lzSXcyQ2ZoKzhUMlAzMEhWU2JxT1VzNG1OblBaWUNVNmdVT3k3YmM1MjlvZ0x3OApHR21UV25WR3JCWVhUbkFnQTFyMGxsMFExTlVvWXU2alJHWG5nUE1odlRNNkFFT3RvVU04Y3hqZEdSNEFteE1mCmFOQWNRRU5KUGpHcjV5NUFQeEsyVGFpVWxROU1OV2h4M2xHT3NHK2NMa0NBZ1RyQVpVejN2Q0ZGRkRWb1pMSFUKaDJ4cnlmQi9iaGx0b2pISklvV0JBb0lCQVFENFlwYmF5VnJlVkM1U3lyMmZvelg2Uys5a3dsOWxMUTJ4MG80Kwp4TytQdXFFM0R1Uy9RNmZEb2Jmd21ONEo1c2tyT09Nb0tFNG5uSFN6RHgxek9ybEo5MzBkZzdjMjI3cS9Nc29nCnlLY28yb1VpQ1N4TGczSTRSaUdwRXJmVGlhT3h0K0wxbTl6eElqbnhxR09mZlBNWjdXNGtNOVdSakhrbU94SlYKcDNKS0h6Smk0TmVMUEtjdmpJTUFQMUgwKzZsckRwV0x3MDdRUlVqRFBhSHI0RWZPdi9PR3hEbW5HMmU2OXVzdgpicmMzaE9ySzU0SVZheVVRQnNVeU9mUlQybnMvSTJBOWNQTFgvd2N6MWp3SUkwUUxjRWdWSlJtNHpubDhpa2NuCmxnbEY5UHcvL3ZjRS8xRFFydzMvbk0xOEt4OGd1SnNsUGg2dDlDYkoyNjlxOG9sRkFvSUJBUUROaGtGei96YlcKM3ZLOGtSN0JYMWRDVHZwY2Z4cFlibTRGL21BQU0vWXBnaHVuck1uaDNRdUcxa2lBbmRWRkpIQ2hMaVpwQlZWNwpZZXR2WHh4SHIzNkVlbkJpZW9hV01Jc1RUS3ovUUZ2R25SUGJWOUhVaTBxVi9PcTY5clI3TmJoWnNvNzhuWTFMCjM2WUdWU055b2x3aHFWLzAzaHB6RHRRWjFvWDVVWkhHNjVpZ09tVGFBbmFFWlVBUFlib2RkRmRVNVRUYkhYSm8KZS9JV2t3eWtNNWN1aXBZemZ4Q3dJcWFnWUpJaVNrcjNveXVqQUMxM1BxRGpYb0l1MXAwRkpBTTFEVmtQNkNQeQoxMmZMQTlpYS93UW1TZkNteU5BMlFkZGpJN015T0VINzdJbkFkMDFLMXZRRUZNb28yT2VRMXpzMWZCRVZyUmIwClh2ME9WTWR6WDJwaEFvSUJBRkxmUWduWmFMSUpVRE5iWlkwZnZXQzNlVFliREEwTHpTZnBZb0JhNExzSnY4UkkKK2RVKzAzaVlPbkRSOEROSmh4RWV0OXVzSnZkY1lpdGovYVYya0YrM2JVMHRwekZzZXBCVWQ5QWNZbmxrLzBwdAoyUk9RMWNra3pSSkdKb016eHlRQ2dIMEY5ZCtXVmRMbEplZ09ubVdtTER0ejkrdkovSm5lMTYwd1l4ZUw5Um04CmZ1MzczS1FtczRhZm1jNnRNTWVCWkMvdmlCcEJJNWZRdG5lbXF3NjJTS0JNVkJnSE1zTFVvMzk5NXk5azc1bW4KU0dXeEMvcWU1NmhzWWJLZ2tNSnVJU3dleFVkLzFYMWNHMGR6ekw0c1JrQ1gwazh3eEtQaTF2N0VObS9hMzFiUwowTVFnRTJ5dEczU1BjcGZkSTFPZGhGWVd0ZEhBUmpqUFRXWFhhaWtDZ2dFQVR2NzVqWUpkSzczS0F4eXNlNXNQCnlSYmVPRXRLYnc4VER3NjFDNTd0VVFzSFlpMlI4MVNwSjR5WmxZWVZBVngrUmhXZEFlVGc5R213dXNBTitLZkYKczFuMGRJV3YwVzZiSmpIa2xML0NCdGM5V0tPcXJVMVV2ODNVMDBRY0h2ZUpBa0VWb0pkV1JnR1NxUUIwZlkxVwphRUhYOWlDZ2ZmVUhKVjlGWTQwc3dRNnhQWFQwYXE5anFvUFlXWkV3bmoybmk2UUY2dXFvbk94M0lxSW15NzVnCnI2enBDcVllWGZVVG9yVTd0aDVrTGtiemNOV1NwRERZV2t4ck1XR2dQT2VZcS8yVGEvL0lRWUQyRGh4T1YxVUoKM1VXeVVBa0RycmNqK0tFeU1XMWFQMkN0bWVMQlBMRGVYZXMzd1BlT0dpZ0FSQkNKNkpEOUw3U0xBOFVtWEh3aQpRUUtDQVFCK0Vpcm0yOTVMOTR3TFBVWE9RVmVJaUVVYjNlTUVyS3YxSk50eWx0dnlXeFVJd2RCWThPeXhlT0wxCmZjUzZyZUwxalFNMytuUnVQUnZQK0pxRUpIU3NSU1dlRlBJQnhhWHFZck9IVDZaYndNY1htbWtYaG8xQmRDeHYKWmxLVTVUYVpoYXZWZzh0a3lnc0Uya2g5cmdLbUVXb3o4S1QveCtxYlZrNFdjYmFSR0ZDaXp0VGhTTlB6NERmbgpKYnRQdUU2YjVPdVVNNFVFcFZlTVh4d1hxNmZQbGhsUFlNd2ppL2p6TEkraE42TkpxcFlsQml3Z0ZUS2h5Rm5tCkJwYmtMQVcxQ25DdzlGQktuL0g2SjN1Z21HNisvUFp2Y2dYYy9hUUtoeFF0a1JXUVhENjdoUnp6Ykk0SWJTY2cKZEVSS0cxaFRkUnZKMXNLVEJUdWVid2o0MEJzSwotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: moove-tls-cert
type: kubernetes.io/tls
{{- end }}