apiVersion: v1
kind: ConfigMap
metadata:
  name: charles-postgres
  {{- if not .Values.postgresql.enabled }}
  annotations:
      "helm.sh/hook": "pre-install"
  {{- end }}
data:
  charles-init.sh: |
    #!/bin/bash
<<<<<<< HEAD
    export PGUSER=postgres
    export PGPASSWORD=firstpassword
    psql -c "CREATE DATABASE charlescd_butler"
    psql -c "CREATE USER charlescd_butler WITH PASSWORD '3f2Yq8R4HhDCnefR'"
    psql -c "ALTER DATABASE charlescd_butler OWNER TO charlescd_butler"
    psql -d charlescd_butler -c "CREATE EXTENSION IF NOT EXISTS pgcrypto"
    psql -c "CREATE DATABASE charlescd_moove"
    psql -c "CREATE USER charlescd_moove WITH PASSWORD '7Qs2KuM9gYzw48BS'"
    psql -c "ALTER DATABASE charlescd_moove OWNER TO charlescd_moove"
    psql -d charlescd_moove -c "CREATE EXTENSION IF NOT EXISTS pgcrypto"
    psql -c "CREATE DATABASE charlescd_villager"
    psql -c "CREATE USER charlescd_villager WITH PASSWORD 'ZkQ67Lnhs2bM3MPN'"
    psql -c "ALTER DATABASE charlescd_villager OWNER TO charlescd_villager"
    psql -d charlescd_villager -c "CREATE EXTENSION IF NOT EXISTS pgcrypto"
    psql -c "CREATE DATABASE keycloak"
    psql -c "CREATE USER keycloak WITH PASSWORD 'DCWYW66Mq2ca6w8u'"
    psql -c "ALTER DATABASE keycloak OWNER TO keycloak"

    psql -c "CREATE DATABASE charlescd_compass"
    psql -c "CREATE USER charlescd_compass WITH PASSWORD 'C1UinUu6N0vc'"
    psql -c "ALTER DATABASE charlescd_compass OWNER TO charlescd_compass"
    psql -d charlescd_compass -c "CREATE EXTENSION IF NOT EXISTS pgcrypto"

    psql -c "CREATE DATABASE charlescd_gate"
    psql -c "CREATE USER charlescd_gate WITH PASSWORD 'Z2F0ZQo='"
    psql -c "ALTER DATABASE charlescd_gate OWNER TO charlescd_gate"
=======
    {{- if .Values.postgresql.enabled -}}
    {{- range .Values.CharlesApplications -}}
    {{ if .database }}
      psql -c "CREATE DATABASE {{ .database.name }}"
      psql -c "CREATE USER {{ .database.user }} WITH PASSWORD '{{ .database.password }}'"
      psql -c "ALTER DATABASE {{ .database.name }} OWNER TO {{ .database.user }}"
      psql -d {{ .database.name }} -c "CREATE EXTENSION IF NOT EXISTS pgcrypto"
    {{ end }}
    {{- end -}}
    {{ if .Values.keycloak.enabled }}
      psql -c "CREATE DATABASE {{ .Values.keycloak.database.name }}"
      psql -c "CREATE USER {{ .Values.keycloak.database.user }} WITH PASSWORD '{{ .Values.keycloak.database.password }}'"
      psql -c "ALTER DATABASE keycloak OWNER TO keycloak"
    {{ end }}
    {{ else }}
    export PGUSER={{ .Values.postgresql.pguser }}
    export PGPASSWORD={{ .Values.postgresql.pgpassword }}
    {{- range .Values.CharlesApplications -}}
    {{ if .database }}
    psql -h $PGHOST -U $PGUSER -c "CREATE DATABASE {{ .database.name }}"
    psql -h $PGHOST -U $PGUSER -c "CREATE USER {{ .database.user }} WITH PASSWORD '{{ .database.password }}'"
    psql -h $PGHOST -U $PGUSER -c  "ALTER DATABASE {{ .database.name }} OWNER TO {{ .database.user }}"
    psql -h $PGHOST -U $PGUSER -d {{ .database.name }} -c "CREATE EXTENSION IF NOT EXISTS pgcrypto"
    {{ end }}
    {{- end -}}
    {{ if .Values.keycloak.enabled }}
    psql -h $PGHOST -U $PGUSER -c "CREATE DATABASE {{ .Values.keycloak.database.name }}"
    psql -h $PGHOST -U $PGUSER -c "CREATE USER {{ .Values.keycloak.database.user }} WITH PASSWORD '{{ .Values.keycloak.database.password }}'"
    psql -h $PGHOST -U $PGUSER -c  "ALTER DATABASE keycloak OWNER TO keycloak"
    {{ end }}
    {{ end }}
>>>>>>> 90f2d0fbb1f3f2a143b4b0e1d83335d3dadb5ec1
