apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: octopipe-db
spec:
  serviceName: "octopipe-db"
  replicas: 1
  selector:
    matchLabels:
      app: octopipe-db
  template:
    metadata:
      labels:
        app: octopipe-db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        envFrom:
          - configMapRef:
              name: postgres-config-octopipe
        ports:
        - containerPort: 5432
          name: tcp-postgresql
          protocol: TCP
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /bitnami/postgresql
          name: data
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 1Gi
        name: dshm
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      volumeMode: Filesystem
    status:
      phase: Pending
