apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: metacontroller
subjects:
    - kind: ServiceAccount
      name: metacontroller
      namespace: {{ .Release.Namespace }}
roleRef:
    kind: ClusterRole
    name: metacontroller
    apiGroup: rbac.authorization.k8s.io