apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: metacontroller
rules:
    - apiGroups:
          - "*"
      resources:
          - "*"
      verbs:
          - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: aggregate-metacontroller-view
    labels:
        rbac.authorization.k8s.io/aggregate-to-admin: "true"
        rbac.authorization.k8s.io/aggregate-to-edit: "true"
        rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
    - apiGroups:
          - metacontroller.k8s.io
      resources:
          - compositecontrollers
          - controllerrevisions
          - decoratorcontrollers
      verbs:
          - get
          - list
          - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: aggregate-metacontroller-edit
    labels:
        rbac.authorization.k8s.io/aggregate-to-admin: "true"
        rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
    - apiGroups:
          - metacontroller.k8s.io
      resources:
          - controllerrevisions
      verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch