apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: metacontroller
  name: {{ .Release.Name }}-metacontroller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: metacontroller
  serviceName: ""
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metacontroller
    spec:
      serviceAccountName: metacontroller
      containers:
      - name: metacontroller
        image: metacontrollerio/metacontroller:v1.4.7
        command: ["/usr/bin/metacontroller"]
        args:
        - --logtostderr
        - -v=8
        - --discovery-interval=20s
        - --cache-flush-interval=5m
  volumeClaimTemplates: []