version: "3"
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: octopipe
      MONGO_INITDB_ROOT_PASSWORD: octopipe
    ports:
      - "27017:27017"
    volumes:
      - "./data/mongo:/var/lib/mongo/data"