replicaCount: 1
image:
  repository: quiz-app-backend
  tag: latest
  blueTag: latest
  
appname: quiz-app-backend

service:
  name: quiz-app-backend
  type: ClusterIP
  ports:
   - name: http
     port: 8080
configmaps:
  enabled: false
startcommand: 
  enabled: false
ingress:
  enabled: false
resources:
   limits:
    cpu: 1
    memory: 1536Mi
   requests:
    cpu: 128m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
imageCredentials: []
livenessProbe:
  enabled: true
  failureThreshold: 3
  httpGet:
    path: /v1/healthcheck
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /v1/healthcheck
    port: 8080
    scheme: HTTP  
  initialDelaySeconds: 30
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 1   

istio:
  enabled: true

