apiVersion: v1
kind: Service
metadata:
  name: octopipe-mongo
  labels:
    app: octopipe-mongo
spec:
  ports:
  - port: 27017
    name: octopipe-mongo
  clusterIP: None
  selector:
    app: octopipe-mongo