apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: octopipe-mongo
spec:
  serviceName: "octopipe-mongo"
  replicas: 1
  selector:
    matchLabels:
      app: octopipe-mongo
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: octopipe-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        envFrom:
          - configMapRef:
              name: octopipe-mongo-config
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /bitnami/mongodb
          name: data
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 1Gi
        name: dshm
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      volumeMode: Filesystem
    status:
      phase: Pending
