name: build circle-matcher

on:
  push:
    branches: [ main ]
    paths:
      - 'circle-matcher/**'
    tags: 
      - '!*'
  pull_request:
    branches: [ main, charlescd-release-*.0 ]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'circle-matcher/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e
      - name: Set up GraalVM
        uses: DeLaGuardo/setup-graalvm@a766aa7b5fcc0a801fa3d4fd521ca299c03c9c00
        with:
          graalvm-version: '21.0.0.java11'
      - uses: actions/cache@70655ec8323daeeaa7ef06d7c56e1b9191396cbe
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('./circle-matcher/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B clean install -Djfr.unsupported.vm=true
        working-directory: ./circle-matcher
      - name: Tests coverage
        uses: codecov/codecov-action@29386c70ef20e286228c72b668a06fd0e8399192
        with:
          file: ./circle-matcher/target/site/jacoco/jacoco.xml
          flags: circlematcher
          fail_ci_if_error: true
      - name: Check Code Style
        run: mvn checkstyle:checkstyle
        working-directory: ./circle-matcher
      - name: Horusec Security
        working-directory: ./circle-matcher
        run: |
          curl -fsSL https://horusec-cli.s3.amazonaws.com/install.sh | bash
          horusec start -p ./
