name: build circle-matcher

on:
  push:
    branches: [ master ]
    paths:
      - 'circle-matcher/**'
    tags: 
      - '!*'
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'circle-matcher/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('./circle-matcher/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B package
      working-directory: ./circle-matcher
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v0.0.1
      env:
        JAVA_HOME: ''
      with:
        host: qualitygate.charlescd.io
        projectBaseDir: ./circle-matcher
        login: ${{secrets.CHARLESCD_QUALITY_GATE_TOKEN}}
        password: ' '
