name: build gate

on:
  push:
    branches: [main, fix-unpinned-dependencies]
    paths:
      - "gate/**"
    tags:
      - "!*"
  pull_request:
    branches: [ system-token, main, charlescd-release-*.0 ]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "gate/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Go
        uses: actions/setup-go@331ce1d993939866bb63c32c6cbbfd48fa76fc57
        with:
          go-version: "1.15"

      - name: Run Unit tests
        working-directory: ./gate
        run: |
          go test -v -coverpkg ./internal/domain,./internal/use_case/... -coverprofile=coverage.cov ./tests/...

      - name: Tests coverage
        uses: codecov/codecov-action@29386c70ef20e286228c72b668a06fd0e8399192
        with:
          file: ./gate/coverage.cov
          flags: gate
          fail_ci_if_error: true

      - name: Code Style
        uses: docker://morphy/revive-action@sha256:a59182c8da300ca49b40d877a22bcdbc64aa6c9bd405c6cd0674f56b59e34202
        with:
          config: ./gate/revive.toml
          path: "./gate/..."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Horusec Security
        working-directory: ./gate
        run: |
          curl -fsSL https://horusec-cli.s3.amazonaws.com/install.sh | bash
          horusec start -p ./
