name: GoPublish

on:
  release:
    branches: [ master ]

jobs:

  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    
    - name: Build
      run: docker build -t octopipe/octopipe:latest -f cmd/octopipe/Dockerfile .
      
    - name: Login
      run: docker login -u "mayconjrpacheco" -p "99103457"

    - name: Tag versions
      run: docker tag octopipe/octopipe:latest octopipe/octopipe:${{ steps.get_version.outputs.VERSION }}

    - name: Push Version
      run: docker push octopipe/octopipe:${{ steps.get_version.outputs.VERSION }}

    - name: Push Latest
      run: docker push octopipe/octopipe:latest
