name: GoPublish

on:
  release:
    branches: [ master ]

jobs:

  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Generate image
      uses: docker/build-push-action@v1
      with:
        username: mayconjrpacheco
        password: 99103457
        repository: octopipe/octopipe
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
        dockerfile: ./cmd/octopipe/Dockerfile
