name: GoPublish

on:
  release:
    branches: [ master ]

jobs:

  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build
      run: docker build -t octopipe/octopipe:0.1.1 -f cmd/octopipe/Dockerfile .
      
    - name: Login
      run: docker login -u "mayconjrpacheco" -p "99103457"

    - name: Push
      run: docker push octopipe/octopipe:0.1.1
