name: GoPublish

on:
  release:
    branches: [ master ]

jobs:

  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: docker build
      uses: actions/docker/cli@master
      with:
        args: build -t octopipe/octopipe:0.1.1 -f cmd/octopipe/Dockerfile .
    - name: docker login
      uses: actions/docker/login@master
      env:
        DOCKER_PASSWORD: 99103457
        DOCKER_USERNAME: mayconjrpacheco
    - name: docker push
      uses: actions/docker/cli@master
      with:
        args: push octopipe/octopipe:0.1.1
