# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build villager

on:
  push:
    branches: [ main ]
    paths:
      - 'villager/**'
    tags: 
      - '!*'
  pull_request:
    branches: [ main, charlescd-release-*.0 ]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'villager/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Set up JDK 1.11
      uses: actions/setup-java@3bc31aaf88e8fc94dc1e632d48af61be5ca8721c
      with:
        java-version: 1.11
    - uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('./villager/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build
      run: mvn -B clean install
      working-directory: ./villager
    - name: Tests coverage
      uses: codecov/codecov-action@29386c70ef20e286228c72b668a06fd0e8399192
      with:
        file: ./villager/target/site/jacoco/jacoco.xml
        flags: villager
        fail_ci_if_error: true
    - name: Code style
      run: mvn checkstyle:checkstyle
      working-directory: ./villager
    - name: Horusec Security
      working-directory: ./villager
      run: |
        curl -fsSL https://horusec-cli.s3.amazonaws.com/install.sh | bash
        horusec start -p ./

